openapi: 3.0.3
info:
  title: OpenTDF
  license:
    name: BSD 3-Clause Clear
    url: 'https://github.com/opentdf/backend/blob/main/LICENSE'
    version: 1.0.11
  x-logo:
    url: 'https://avatars.githubusercontent.com/u/90051847?s=200&v=4'
