name: Create Release after PR
on:
  push:
    branches:
      - main
jobs:
  job:
    permissions:
      contents: write
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo Release after merge